# This workflow will build RSMPGS1 and RSMPGS2 and create installer

name: Build installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  SXL: rsmp_schema/schemas/tlc/1.1/sxl.yaml
  SITE: sxl-tools/tlc/SXL_Traffic_Controller_ver_1_1-site.yaml

jobs:
  create_sxl:
    name: Create SXL
    runs-on: windows-2019

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies 
        run: pip install xlsxwriter

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install ruby dependencies
        run: gem install rubyXL

      - name: Checkout rsmp_schema
        uses: actions/checkout@v3
        with:
          repository: rsmp-nordic/rsmp_schema
          path: rsmp_schema

      - name: Checkout sxl-tools
        uses: actions/checkout@v3
        with:
          repository: rsmp-nordic/sxl-tools
          path: sxl-tools

      - name: Adapt data types for Core 3.2
        run: |-
          # Convert "timestamp" to "string", because it doesn't officially
          # exist in 3.2
          (Get-Content $env:SXL) -match 'type: timestamp' -replace 'type: string' | Set-Content $env:SXL -WhatIf
          # Remove any trailing _list because it is only used for comma
          # separated values during schema validation
          (Get-Content $env:SXL) -match '_list' -replace '' | Set-Content $env:SXL -WhatIf

      - name: Create YAML file
        run: ruby sxl-tools/merge_yaml.rb --objects $env:SXL --site $env:SITE | Set-Content -Path SXL-example.yaml

      - name: List installed python modules
        run: pip list -v

      - name: Create XLSX template
        run: python sxl-tools/create_template.py

      - name: Create XLSX file
        run: ruby sxl-tools/yaml2xlsx.rb --template RSMP_Template_SignalExchangeList.xlsx --objects $env:SXL --site $env:SITE --stdout | Set-Content -Path SXL-example.xlsx

      - name: Create CSV files
        run: ruby sxl-tools/xlsx2csv.rb SXL-example.xlsx

      - name: Upload artifacts (YAML)
        uses: actions/upload-artifact@v3
        with:
          name: SXL YAML
          path: SXL-example.yaml

      - name: Upload artifacts (XLSX)
        uses: actions/upload-artifact@v3
        with:
          name: SXL XLSX
          path: SXL-example.xlsx

      - name: Upload artifacts (CSV)
        uses: actions/upload-artifact@v3
        with:
          name: SXL CSV
          path: Objects/

  setup:
    name: Create Installer
    runs-on: windows-2019
    steps:
      - name: Install rst2pdf
        run: pip install rst2pdf

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build RSMPGS1 (Release)
        run: msbuild /p:Configuration=Release RSMPGS1/RSMPGS1.sln
        # path: RSMPGS1/bin/Release/RSMPGS1.exe

      - name: Build RSMPGS2 (Release)
        run: msbuild /p:Configuration=Release RSMPGS2/RSMPGS2.sln
        # path: RSMPGS2/bin/Release/RSMPGS2.exe

      - name: Convert manual with rst2pdf
        run: |-
          rst2pdf Documents/Manual_RSMPGS1.rst
          rst2pdf Documents/Manual_RSMPGS2.rst

      - name: Building the installer (RSMPGS1)
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "install_script_rsmpgs1.iss"
        shell: cmd

      - name: Building the installer (RSMPGS2)
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "install_script_rsmpgs2.iss"
        shell: cmd

      - name: Upload setup files
        uses: actions/upload-artifact@v3
        with:
          name: Setup
          path: Output/*.exe

      - name: Upload manuals
        uses: actions/upload-artifact@v3
        with:
          name: Manual
          path: |-
            Documents/Manual_RSMPGS1.pdf
            Documents/Manual_RSMPGS2.pdf
