# This workflow will build RSMPGS1 and RSMPGS2 and create installer

name: Build installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  setup:
    name: Create Installer
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build RSMPGS1 (Release)
        run: msbuild /p:Configuration=Release RSMPGS1/RSMPGS1.sln
        # path: RSMPGS1/bin/Release/RSMPGS1.exe

      - name: Build RSMPGS2 (Release)
        run: msbuild /p:Configuration=Release RSMPGS2/RSMPGS2.sln
        # path: RSMPGS2/bin/Release/RSMPGS2.exe

      - name: Building the installer (RSMPGS1)
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "install_script_rsmpgs1.iss"
        shell: cmd

      - name: Building the installer (RSMPGS2)
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "install_script_rsmpgs2.iss"
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: Output/RSMPGS1_1_0_1_7_Setup.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: Output/RSMPGS2_1_0_1_7_Setup.exe
