# This workflow will build RSMPGS1 and RSMPGS2 and create installer

name: Build RSMPGS1 and RSMPGS2 using Mono

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  rsmpgs1:
    name: Build RSMPGS1
    runs-on: windows-latest
    needs: prerequisites
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build RSMPGS1 (Debug)
        run: xbuild RSMPGS1/RSMPGS1.sln

      - name: Build RSMPGS1 (Release)
        run: xbuild /p:Configuration=Release RSMPGS1/RSMPGS1.sln

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "RSMPGS1\Setup\install_script.iss"
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RSMPGS1
          path: RSMPGS1_1_0_1_7_Setup.exe

