# This workflow will build RSMPGS1 and RSMPGS2 and create installer

name: Build installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build RSMP Simulator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build RSMPGS1 (Release)
        run: xbuild /p:Configuration=Release RSMPGS1/RSMPGS1.sln

      - name: Build RSMPGS2 (Release)
        run: xbuild /p:Configuration=Release RSMPGS2/RSMPGS2.sln

      - uses: actions/upload-artifact@v2
        with:
          name: exe
          path: |
            RSMPGS1/bin/Release/RSMPGS1.exe
            RSMPGS2/bin/Release/RSMPGS2.exe
  setup:
    name: Create Installer
    runs-on: windows-latest
    needs: build
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: exe
          path: Setup

      - name: Check Setup directory
        run: ls Setup/RSMPGS1
        shell: powershell

      - name: Building the installer (RSMPGS1)
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Setup\install_script_rsmpgs1.iss"
        shell: cmd

      - name: Building the installer (RSMPGS2)
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Setup\install_script_rsmpgs2.iss"
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Setup
          path: Setup/Output/*.exe
